### ISSUE TITLE
Translated graphics to EN website? 

### ISSUE THREAD

**Issue by ondraspribyla** [faktaoklimatu/web-en#3]
We have few graphics (+ texts?) that are already translated to EN. Lets find a way to put them to the website as samples...

**Comment by kikinna** [comment]
Here's a list of graphics already translated into English. 

What needs to be done to put them online?
* I am thinking of asking Jirka to proofread them (in case we haven't had a proper proofread already)
* We need to create english slug for each graphic and also edit it inside the graphic itself


Energetics
* [Per capita electricity production in the EU](https://github.com/faktaoklimatu/graphics/blob/main/data-visualization/energetics/european-union/per-capita-electricity-production-in-the-eu/en-per-capita-electricity-production-eu.pdf)
* [Electricity production, consumption and emissions](https://github.com/faktaoklimatu/graphics/blob/main/data-visualization/energetics/czechia/electricity-production,-consumption-and-emissions-in-czechia/en-electricity-czechia.pdf)
* [Coal phase-out in the EU countries](https://github.com/faktaoklimatu/graphics/blob/main/data-visualization/energetics/european-union/coal-phase-out/en-coal-phase-out-eu.pdf)

Transformation studies
* [Comparison: Czech Electricity transition studies](https://github.com/faktaoklimatu/graphics/blob/main/data-visualization/energetics/czechia/transition-studies-comparison/en-transition-studies-comparison.pdf)
* [Energynautics](https://github.com/faktaoklimatu/graphics/blob/main/data-visualization/energetics/czechia/czech-electricity-transition-studies/en-2018-study-energynautics.pdf)
* [Bloombergnef](https://github.com/faktaoklimatu/graphics/blob/main/data-visualization/energetics/czechia/czech-electricity-transition-studies/en-2020-study-bloomberg.pdf)
* [Ember](https://github.com/faktaoklimatu/graphics/blob/main/data-visualization/energetics/czechia/czech-electricity-transition-studies/en-2020-study-ember.pdf)
* [NECP](https://github.com/faktaoklimatu/graphics/blob/main/data-visualization/energetics/czechia/czech-electricity-transition-studies/en-2019-study-necp.pdf)


Emissions
* [Ghg emissions in Czechia by sectors detail](https://github.com/faktaoklimatu/graphics/blob/main/data-visualization/emissions/czechia/ghg-emissions-in-czechia-by-sector/en-emissions-czechia-detail.pdf)
* [Ghg emissions in Czechia by sectors](https://github.com/faktaoklimatu/graphics/blob/main/data-visualization/emissions/czechia/ghg-emissions-in-czechia-by-sector/en-emissions-czechia.pdf)
* [Emission pathways towards paris agreement](https://github.com/faktaoklimatu/graphics/blob/main/data-visualization/emissions/world/emission-pathways-paris/en-emission-pathways-paris.pdf)
* [Fossil Fuels Emissions](https://github.com/faktaoklimatu/graphics/blob/main/data-visualization/emissions/world/fossil-fuels-emissions/en-fossil-fuels-emissions.pdf)

Climate indicators
* [Schema of climate change](https://github.com/faktaoklimatu/graphics/blob/main/data-visualization/climate-indicators/world/schema-of-climate-change/en-climate-change-schema.pdf)

**Comment by mukrop** [comment]
Hmm, that's many more than I expected! Though I presume we miss translated website texts related to these?

Since the Slovak version was already split and there is more infgraphics than just a few, I would suggest to do a full website version (just as the Slovak version is).

Is it worth having Jirka translate the accompanying texts?

**Comment by katkolouch** [comment]
Some of the graphics were already proofread by Jirka in the past, these include:
- Per capita electricity production in the EU
- Comparison of per capita GHG emissions
- Electricity production, consumption and emissions
- Coal phase-out in the EU countries
- Ghg emissions in Czechia by sectors

The rest of them were proofread by some of us, however, I think we could ask Jirka to go through them again and also check if we use consistent terminology throughout the translations (e. g. Jirka suggested to use crude oil instead of just oil etc.).

Regarding the accompanying texts – in my opinion it would be great to have the texts translated at some point, however for the time being we could publish just graphics and their captions. What do you think?

I don't know about the datasets though. We could add a disclaimer saying that our datasets are available in Czech only. Or we could link only original datasets as most of them are in English.

**Comment by mukrop** [comment]
These all should be online now, closing the issue.
